### ISSUE TITLE
Problems with WonderCMS 2.0.0

### ISSUE THREAD

**Issue by robiso** [prakai/wcms-addition_contents#1]
We released WonderCMS 2.0.0 and 2.0.1 and some of the hooks seem to be wrongly named on this version.

Additionally, any changes made to the index.php will cause them to be overwritten in the next update, so users will end up getting an error.

Do you rather suggest we add additional hooks?

**Comment by turboblack** [comment]
The plugin is excellent, I want to offer one important addition to it.
In the presence of long articles, like in a blog, the page becomes very long.
Is there an opportunity to do that the article would not open completely at once, but only the top of it, let's say the first 5 lines, and the button that would open it completely?
